lib/hw06_web/router.ex
defmodule Hw06Web.Router do
  use Hw06Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Hw06Web.Plugs.FetchSession
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Hw06Web do
    pipe_through :browser

    get "/", PageController, :index
    resources "/tasks", TaskController
    resources "/users", UserController
    resources "/sessions", SessionController, only: [:delete, :create], singleton: true
  end

  # Other scopes may use custom stacks.
  # scope "/api", Hw06Web do
  #   pipe_through :api
  # end
end

lib/hw06_web/views/layout_view.ex
defmodule Hw06Web.LayoutView do
  use Hw06Web, :view
end

lib/hw06_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <title>Task Viewer</title>
    <link rel="stylesheet" href="<%= Routes.static_url(@conn, "/css/app.css") %>"/>
  </head>
  <body>
    <div class="container">
     <nav class="navbar navbar-expand-sm navbar-light bg-white">
       <div class="col-4">
         <a class="navbar-brand" href="#">Tasks Viewer</a>
       </div>
       <div class="col-4">
         <ul class="navbar-nav mr-auto">
           <li class="nav-item active">
             <a class="nav-link" href="/">Home</a>
           </li>
           <li class="nav-item">
             <a class="nav-link" href="/tasks">Tasks</a>
           </li>
         </ul>
       </div>
       <div class="col-4">
      <%= if @current_user do %>
        <p class="my-3">
          User: <%= @current_user.name %> |
          <%= link("Logout", to: Routes.session_path(@conn, :delete),
            method: :delete) %>
        </p>
      <% else %>
        <%= form_for @conn, Routes.session_path(@conn, :create),
                [class: "form-inline"], fn f -> %>
          <%= text_input f, :name, class: "form-control" %>
          <%= submit "Login", class: "btn btn-secondary" %>
        <% end %>
      <% end %>
    </div>
     </nav>

     <div class="row">
       <div class="col-12">
         <%= if get_flash(@conn, :info) do %>
           <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
         <% end %>
         <%= if get_flash(@conn, :error) do %>
           <p class="alert alert-danger" role="alert">
             <%= get_flash(@conn, :error) %>
           </p>
         <% end %>
       </div>
     </div>

     <%= render @view_module, @view_template, assigns %>
   </div>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>